version: "3.9"
services:
  data:
    image: "postgres:12.3"
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: cars
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - data
volumes:
  postgres-data:
